language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
  - "CODECLIMATE_REPO_TOKEN=e411d8c7652cd4d4796d0d80b1957a7683045ad71fdfafc5b2238122386183a9 ./node_modules/.bin/codeclimate < ./coverage/lcov.info"
